const actions = {
  GET_INGREDIENT_LIST_REQUEST: 'GET_INGREDIENT_LIST_REQUEST',
  GET_INGREDIENT_LIST_SUCCESS: 'GET_INGREDIENT_LIST_SUCCESS',
  GET_INGREDIENT_LIST_FAILURE: 'GET_INGREDIENT_LIST_FAILURE',

  getIngredientList: () => ({ 
    type: actions.GET_INGREDIENT_LIST_REQUEST
  })
};

export default actions;